name: Linux,macOS build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        platform: [x64]
        PLAT: [arm64, x86_64, universal2]
        INTERFACE64: ['3.9']
    env:
      REPO_DIR: gmpy2
      MACOSX_DEPLOYMENT_TARGET: 10.9
      MB_PYTHON_VERSION: ${{ matrix.MB_PYTHON_VERSION }}
      TRAVIS_PYTHON_VERSION: ${{ matrix.MB_PYTHON_VERSION }}
      BUILD_DIR: ${{ github.workspace }}
      PLAT: ${{ matrix.PLAT }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Set extra env
      run: |
        if [[ "$(uname)" == "Darwin" ]]; then echo "TRAVIS_OS_NAME=osx" >> $GITHUB_ENV; else echo "TRAVIS_OS_NAME=${{ matrix.os }}" >> $GITHUB_ENV; fi
    - name: Print some Environment variable
      run: |
        echo "TRAVIS_OS_NAME: ${TRAVIS_OS_NAME}"
        echo "PLAT: ${PLAT}"
    - name: Install VirtualEnv
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
    - name: Build and Install Wheels
      run: |
        sudo xcode-select -switch /Applications/Xcode_12.2.app
        source multibuild/common_utils.sh
        source multibuild/travis_steps.sh
        echo "------ BEFORE BUILD ---------"
        before_build
        echo "------ CLEAN CODE --------"
        clean_code $REPO_DIR
        echo "------ BUILD WHEEL --------"
        build_wheel $REPO_DIR $PLAT
